### ISSUE TITLE
BE: save the user score when the game end with a victory

### ISSUE THREAD

**Issue by rubin0** [matteocodogno/CipherQuest#22]
Save the user score in the `score` column when the game ends. 

The score should be a combination of coins left and time spent on the game. 

blocked by #21

**Comment by matteocodogno** [comment]
With @mangialavorisara and  Ignazio, we computed the final score using the following formula.

<img width="1137" alt="image" src="https://github.com/user-attachments/assets/80a70c08-9bbf-4034-b15b-a1d90e17a6a4">
